document.writeln("<!--上方導覽列-->");
document.writeln("	<nav class=\'navbar navbar-dark bg-dark fixed-top\'>");
document.writeln("		<span class=\'navbar-brand fontTitle \'>網路安全作業區</span>");
document.writeln("		<ul class=\'nav justify-content-end\'>");
document.writeln("			<li class=\'nav-item\'>");
document.writeln("				<a class=\'text-light nav-link fontTitle\' href=\'intro.htm\'>個人介紹</a>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</nav>");
document.writeln("	<!--左側導覽列-->");
document.writeln("	<div class=\'sidenav mt-5 fontTitle\'>");
document.writeln("		<title>課堂作業</title>");
document.writeln("		<a href=\'ex1.html\'>作業一：社交工程</a>");
document.writeln("		<a href=\'ex2.html\'>作業二：Archive</a>");
document.writeln("		<a href=\'#\' data-toggle=\'collapse\' data-target=\'#collapse1\' aria-expanded=\'true\' aria-controls=\'collapse1\'>作業三：HTTrack</a>");
document.writeln("		<div id=\'collapse1\' class=\'collapse\' aria-labelledby=\'heading1\' data-parent=\'#accordion\'>");
document.writeln("			<a href=\'CK_TP/index.html\'>");
document.writeln("			    下載網站");
document.writeln("			</a>");
document.writeln("			<a href=\'http://web.ck.tp.edu.tw/web2007/index.php\'>");
document.writeln("			    原本網站");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<a href=\'#\' data-toggle=\'collapse\' data-target=\'#collapse2\' aria-expanded=\'true\' aria-controls=\'collapse1\'>作業四：掃描</a>");
document.writeln("		<div id=\'collapse2\' class=\'collapse\' aria-labelledby=\'heading1\' data-parent=\'#accordion\'>");
document.writeln("			<a href=\'ex4_1.html\'>");
document.writeln("			    Ipscan");
document.writeln("			</a>");
document.writeln("			<a href=\'ex4_2.html\'>");
document.writeln("			    Nessus");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<a href=\'ex5.html\'>作業五：NetCut</a>");
document.writeln("		<a href=\'ex6.html\'>作業六：監聽</a>");
document.writeln("		<a href=\'mid.htm\'>期中報告</a>");
document.writeln("		<a href=\'ex7.html\'>作業七：密碼強度</a>");
document.writeln("		<a href=\'ex8.html\'>作業八：限制連線</a>");
document.writeln("		<a href=\'ex9.html\'>作業九：https練習</a>");
document.writeln("		<a href=\'ex10.html\'>作業十：SQL Injection</a>");
document.writeln("	</div>");